# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_simplin_timesTwo', PACKAGE = 'simplin', x)
}

mean_cpp <- function(x) {
    .Call('_simplin_mean_cpp', PACKAGE = 'simplin', x)
}

#' Efficiently fit a simple linear regression in C++
#' @export
#' @param x Vector of covariate observations
#' @param y Vector of response observations
#' @returns An Rcpp List object containing model elements.
simp_lin_cpp <- function(x, y) {
    .Call('_simplin_simp_lin_cpp', PACKAGE = 'simplin', x, y)
}

